version: "2.2"
services:
  plantuml:
    image: 'bitjourney/plantuml-service:1.3.3'

  gitbook:
    image: hero/gitbook:latest
    volumes:
      - ./gitbook:/gitbook
    ports:
      - 4000:4000
    depends_on:
      - plantuml
    command: 'serve'
